### ISSUE TITLE
大部分立绘图片复原时出现缝隙

### ISSUE THREAD

**Issue by littleplus** [Goodjooy/AzurLane-PaintingExtract#6]
![2019-04-28 18_11_42_0.png](https://i.loli.net/2019/04/28/5cc57cb830e5f.png)
![2019-04-28 18_11_49_2.png](https://i.loli.net/2019/04/28/5cc57cb84b1bf.png)

**Comment by Goodjooy** [comment]
你导入图片错了

**Comment by littleplus** [comment]
不是将painting文件夹里面的全部文件解压缩以后，导入进去吗？

请教一下是导入什么呢，或者说应该怎么导入呢？

**Comment by Goodjooy** [comment]
你随便选择一个有tex后缀的文件用assetstudio打开，里面有2种不同尺寸的图片，导入的是较大的

**Comment by littleplus** [comment]
![2019-04-28 21_09_08_5.png](https://i.loli.net/2019/04/28/5cc5a6174fea5.png)
只有一个啊？

**Comment by Goodjooy** [comment]
Sprite也是，导入这个会覆盖之前的tex的路径，用筛选器，只保留mesh和Texture2d再导出筛选后的是推荐

**Comment by littleplus** [comment]
噗，原来是这样，解决了，谢谢
